blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

# определяем пространство имен, для текущего приложения, чтобы в шаблоне образаться blog:post_list и т д
app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # этот урл обрабатывается одним и тем же view с первым варинтом, вью обрабатывает наличия tag_slug
    path('feed/', LatestPostFeed(), name='post_feed'),
    # для RSS feed
    path('search/', views.post_search, name='post_search'),
]
# <slug:post> гворит о том, что эта часть урл может состоять из букв или дефисов
# path имеет встроенный конвертор, который из строки делает нужные значения типа int, slug и т д
# создание отдельно урд для каждого приложения делает возможным, чтобы это
# приложение могли комфортно использовать другие

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

# словарь sitemaps
sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # sitemap словарь передвется view sitemap
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Создаем кастомный менеджер моделей, вместо Model.objects
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):

    # draft - значение, Draft отображение в форме
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # Slug (по другому часть URL адреса), используется в моделях для генерации уникального URL для объекта
    # unique_for_date строим URL с помощью publish date и slug,
    # то есть в определенную дату публикации может быть только один уникальный sluf
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    # auto_now_add Дата и время создается при создании объекта
    updated = models.DateTimeField(auto_now=True)
    # auto_now Дата и время добавляется, когда объект сохраняется
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    # choices принимает список с вариантами выбора для текстового поля
    objects = models.Manager()
    # дефолтный менеджер моделей, если мы не задаем дефолтный , то он добавляется автоматисески к каждой модели
    # так как мы добавили кастомный, надо добавить дефолтный чтобы он сохранил свое действие
    published = PublishedManager()
    # наш кастомный менеджер и можем обращаться Post.published.filter(...) фильтрует по уже опубликованным постам
    tags = TaggableManager()
    # систеиа тегов через taggit

    # ordering упорядовачивание объектов при запросе в БД, минус означает что в обратном порядке
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    # метод который возвращает "канонический" урл для модели,
    # используется в шаблонах для обращения к определенному посту, удобно для ссылок сложных
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])
    # reverse создает url


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm

from taggit.models import Tag

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    # задаем кастомное имя для контекста, default = object_list
    paginate_by = 3
    # пагинация объектов по три штуки
    # в шаблоне при покдлючении пагинации page=page_obj
    template_name = 'blog/post/list.html'


# аналогичен верхнему варианту
def post_list(request, tag_slug=None):
    # эта вью может обрабатывать два урл с tag_slug и без
    object_list = Post.published.all()
    # так как queryset ленивый можно не передивать что мы дважды вытаскиваем список объектов (ниже в условиях если тэг),
    # так как он будет выполненен только при рендеринге страницы
    tag = None
    if tag_slug:
        # если tag_slug есть в урл
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
        # tag предаем списоком, чтобы фильтр __in сработал и так как между Post и Tag Many-to-Many
    paginator = Paginator(object_list, 3)
    # создает последовательность Pages с заданным количеством объектов списка те 3 штуки
    # те создавая пагинатор мы получаем возможность в гет запросе получать 'page' значение,
    # так как он есть на всех страницах потому что мы включаем его через include на все страницы
    page = request.GET.get('page')
    # это объект класса Page, page это список объектов на странице
    try:
        posts = paginator.page(page)
        # в шаблоне при покдлючении пагинации page=posts
        # получаем объекты для заданной страницы
    except EmptyPage:
        posts = paginator.page(1)
    except PageNotAnInteger:
        posts = paginator.page(paginator.num_pages)
        # эта ошибка обрабатывает первую загрузку, то есть когда страница еще не может быть обработана
        # возвращает последнюю страницу,
        # т к paginator.num_pages возвращает общее количество страниц
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    # get_object_or_404 так же может фильтровать объект по многим параметрам
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day
                             )
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            # создаем объект комментария без сохранения в БД
            # метод save() можно приенять к формам от ModelForm, просто Form обрабатываются вручную
            new_comment.post = post
            # задаем объекту комеентария поле post
            new_comment.save()
            # и сохраняем в БД
            # редирект отсутвует, происходт перезагрузка на эту же страницу с добавденным комментарием
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    # реккомендация схожих постов по тегу
    # values_list получает QS кортежей объектов с указанными полями, flat=True говорит что если кортеж состоит из
    # одного значения, то иы получаем QS со сзначениями указанного поля. Например <QS[1, 2, 3 ...]>
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # ищем посты с этими тегами, исключая пост в котором мы находимся tags__id__in аналогична tags__in
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    # так как фильтрация идет перед анотацией, поэтому она влияет на нее, и сохранились только общие тэги
    # и это позволяет нам их посчитать(общие)-
    # фильтрация имеет эффект ограничения объектов для которой расчитывается анатоцация
    # фильтруем по большинству совпадений тэгов в посте и делаем максимально 4 рекомендации
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    # используем в шаблоне для алерта для успешной отправки
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        # else обрабатывается автоматически и если неверна то страница перезагружается
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            # строим полный урл адрес, включая хттп доменное имя и поля с помощью build_absolute_url
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            # функция для отправки письма (заголовок, сообщение, от кого, список получателей)
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    # query это название поля в форме, то есть проверяем есть ли запрос в форме
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        # GET запрос так же проверяем на валидность
        if form.is_valid():
            query = form.cleaned_data['query']
            # проводим поиск по заголовку и телу поста
            # имя аргумента в аннотации и в фильтре должны быть одинаковыми, вариант 1
            # results = Post.published.annotate(search=SearchVector('title', 'body'),).filter(search=query)

            # в данном примере мы с помощью SearchQuery(кот-ый имет спец алгоритмы)
            # находим совпадение запросов по корню слов.
            # с помощью SearchRank делаем более эффективную ранжировку совпадений
            # search_vector = SearchVector('title', 'body')
            # search_query = SearchQuery(query)
            # results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)
            #                                   ).filter(search=search_query).order_by('-rank')

            # в данном случае с помощью аргумента weight мы определяем где важнее искать соответсвие
            # в какой Search Vector, то есть таблице, в даннои случае фильтр настроен на rank более 0.3
            # D=0.1, C=0.2, B=0.4, A=1.0
            # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)
            #                                   ).filter(rank__gte=0.3).order_by('-rank')

            # Поиск на основе триграм, то есть трех послеловательных букв с двух строках и считает совпадения
            # Так как во многих языках слова совпадают, это являетя эффективным поиском
            # Для этого в postgres нужно установить pg_trgm
            results = Post.published.annotate(similarity=TrigramSimilarity('title', query),).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
        Share this post
        </a>
    </p>

    <h2>Similar posts</h2>
        {% for post in similar_posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
        {% empty %}
            There are no similar posts yet.
        {% endfor %}
    {% with comments.count as total_comments %} {# задаем кастомное название для метода, удобно когда названия поавторяются #}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }} {# pluralize добавляет comment множественное число в зависимости от числа #}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }} {# forloop.counter значит что каждый раз выводится номер цикла, что в данном случае является номером комментария #}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet</p>
    {% endfor %}
{# empty относится к циклу и показывает код если 0 объектов в цикле #}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with '{{ tag.name }}'</h2>
    {% endif %}
    {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h2>
    <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %} {# если цикл не последний добавляем запятую после тэга #}
            {% endfor %}
        </p>

  {# вариант 2 без ссылок  <p class="tags">Tags: {{ post.tags.all|join:", " }}</p> {# join работает как в питоне - объединение списка в строку через запятую #}

    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }} {# truncateword_html не считает тэги и закрывает их автоматически если они не влезли #}
    {% endfor %}
    {% include "blog/post/pagination.html" with page=posts %} {# page=page_obj для CBV #}
{% endblock %}

blog/templates/blog/post/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>Email successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send email">
        </form>
    {% endif %}
{% endblock %}